# Generated by Django 4.2.29 on 2026-03-09 23:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadEvaluativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fecha', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('carga_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='academico.cargaacademica')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='academico.periodoacademico')),
            ],
            options={
                'verbose_name': 'Actividad evaluativa',
                'verbose_name_plural': 'Actividades evaluativas',
                'ordering': ['-fecha', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='evaluacion.actividadevaluativa')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='academico.estudiante')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['estudiante__apellidos'],
                'unique_together': {('actividad', 'estudiante')},
            },
        ),
    ]
