# Generated by Django 4.2.29 on 2026-03-09 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnioLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Año lectivo',
                'verbose_name_plural': 'Años lectivos',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('intensidad_horaria', models.PositiveSmallIntegerField(default=1)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('director_grupo', models.ForeignKey(blank=True, limit_choices_to={'rol': 'DOC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_dirigidos', to=settings.AUTH_USER_MODEL)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='academico.grado')),
            ],
            options={
                'ordering': ['grado__nombre', 'nombre'],
                'unique_together': {('nombre', 'grado')},
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo_documento', models.CharField(choices=[('TI', 'Tarjeta de identidad'), ('CC', 'Cédula de ciudadanía'), ('RC', 'Registro civil'), ('CE', 'Cédula de extranjería')], default='TI', max_length=2)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('acudiente', models.CharField(max_length=150)),
                ('telefono_acudiente', models.CharField(max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='academico.grupo')),
            ],
            options={
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numero', models.PositiveSmallIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('anio_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='academico.aniolectivo')),
            ],
            options={
                'verbose_name': 'Periodo académico',
                'verbose_name_plural': 'Periodos académicos',
                'ordering': ['anio_lectivo', 'numero'],
                'unique_together': {('numero', 'anio_lectivo')},
            },
        ),
        migrations.CreateModel(
            name='CargaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('anio_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_academicas', to='academico.aniolectivo')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_academicas', to='academico.asignatura')),
                ('docente', models.ForeignKey(limit_choices_to={'rol': 'DOC'}, on_delete=django.db.models.deletion.CASCADE, related_name='cargas_academicas', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_academicas', to='academico.grupo')),
            ],
            options={
                'verbose_name': 'Carga académica',
                'verbose_name_plural': 'Cargas académicas',
                'unique_together': {('docente', 'grupo', 'asignatura', 'anio_lectivo')},
            },
        ),
    ]
