# Generated by Django 4.2.29 on 2026-03-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_alter_estudiante_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='correo_acudiente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='estudiantes/'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='whatsapp_acudiente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
