# Generated by Django 4.2.29 on 2026-04-13 02:53

from django.db import migrations, models


NOMBRES_FEMENINOS = {
    'ANA', 'ANGELA', 'CAMILA', 'CLAUDIA', 'DANIELA', 'DIANA', 'GABRIELA',
    'ISABELLA', 'JULIANA', 'LAURA', 'LUISA', 'LUZ', 'MANUELA', 'MARIA',
    'MARIANA', 'MARTA', 'PAOLA', 'PATRICIA', 'SALOME', 'SARA', 'SOFIA',
    'VALENTINA', 'YULIANA', 'LINA', 'LUCIANA',
}

NOMBRES_MASCULINOS = {
    'ALEJANDRO', 'ANDRES', 'CARLOS', 'DANIEL', 'DAVID', 'EMILIANO', 'JORGE',
    'JUAN', 'MATEO', 'MIGUEL', 'NICOLAS', 'PABLO', 'RICARDO', 'SAMUEL',
    'SANTIAGO', 'SEBASTIAN', 'TOMAS',
}


def poblar_genero_estudiantes(apps, schema_editor):
    Estudiante = apps.get_model('academico', 'Estudiante')

    for estudiante in Estudiante.objects.all():
        primer_nombre = (estudiante.nombres or '').strip().split()
        primer_nombre = primer_nombre[0].upper() if primer_nombre else ''

        if primer_nombre in NOMBRES_FEMENINOS:
            estudiante.genero = 'F'
        elif primer_nombre in NOMBRES_MASCULINOS:
            estudiante.genero = 'M'
        else:
            estudiante.genero = 'O'

        estudiante.save(update_fields=['genero'])


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_estudiante_correo_estudiante_correo_acudiente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro / No especifica')], default='O', max_length=1),
        ),
        migrations.RunPython(poblar_genero_estudiantes, migrations.RunPython.noop),
    ]
