# Generated by Django 4.2.29 on 2026-04-13 03:04

from django.db import migrations, models


NOMBRES_FEMENINOS = {
    'ANA', 'ANGELA', 'CAMILA', 'CLAUDIA', 'DANIELA', 'DIANA', 'GABRIELA',
    'ISABELLA', 'JULIANA', 'LAURA', 'LUISA', 'LUZ', 'MANUELA', 'MARIA',
    'MARIANA', 'MARTA', 'PAOLA', 'PATRICIA', 'SALOME', 'SARA', 'SOFIA',
    'VALENTINA', 'YULIANA', 'LINA', 'LUCIANA',
}

NOMBRES_MASCULINOS = {
    'ALEJANDRO', 'ANDRES', 'CARLOS', 'DANIEL', 'DAVID', 'EMILIANO', 'JORGE',
    'JUAN', 'MATEO', 'MIGUEL', 'NICOLAS', 'PABLO', 'RICARDO', 'SAMUEL',
    'SANTIAGO', 'SEBASTIAN', 'TOMAS', 'FARID', 'SLAYDER', 'JONATAN',
    'JADER', 'ANDERSON', 'YESID', 'JESUS',
}


def normalizar_genero(apps, schema_editor):
    Estudiante = apps.get_model('academico', 'Estudiante')

    for estudiante in Estudiante.objects.all():
        if estudiante.genero in {'M', 'F'}:
            continue

        primer_nombre = (estudiante.nombres or '').strip().split()
        primer_nombre = primer_nombre[0].upper() if primer_nombre else ''

        if primer_nombre in NOMBRES_FEMENINOS:
            genero = 'F'
        elif primer_nombre in NOMBRES_MASCULINOS:
            genero = 'M'
        else:
            genero = 'F' if primer_nombre.endswith('A') else 'M'

        estudiante.genero = genero
        estudiante.save(update_fields=['genero'])


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_estudiante_genero'),
    ]

    operations = [
        migrations.RunPython(normalizar_genero, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='estudiante',
            name='genero',
            field=models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], default='M', max_length=1),
        ),
    ]
