# Generated by Django 4.2.29 on 2026-04-29 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academico', '0007_horarioclase'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(blank=True, limit_choices_to={'rol': 'EST'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_estudiante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cargaacademica',
            index=models.Index(fields=['docente', 'activo'], name='carga_docente_activa_idx'),
        ),
        migrations.AddIndex(
            model_name='cargaacademica',
            index=models.Index(fields=['grupo', 'activo'], name='carga_grupo_activa_idx'),
        ),
        migrations.AddIndex(
            model_name='cargaacademica',
            index=models.Index(fields=['anio_lectivo', 'activo'], name='carga_anio_activa_idx'),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['grupo', 'activo'], name='est_grupo_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['apellidos', 'nombres'], name='est_nombre_idx'),
        ),
        migrations.AddIndex(
            model_name='reporteacudiente',
            index=models.Index(fields=['estudiante', 'periodo', '-fecha_registro'], name='reporte_est_periodo_idx'),
        ),
        migrations.AddIndex(
            model_name='reporteacudiente',
            index=models.Index(fields=['estado', '-fecha_registro'], name='reporte_estado_fecha_idx'),
        ),
    ]
