# Generated by Django 4.2.29 on 2026-03-09 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaTemprana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ASISTENCIA', 'Baja asistencia'), ('RENDIMIENTO', 'Bajo rendimiento'), ('AUSENCIAS', 'Ausencias consecutivas'), ('DESCENSO', 'Descenso académico')], max_length=20)),
                ('nivel', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], max_length=10)),
                ('descripcion', models.TextField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('REVISADA', 'Revisada'), ('CERRADA', 'Cerrada')], default='ACTIVA', max_length=10)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='academico.estudiante')),
            ],
            options={
                'verbose_name': 'Alerta temprana',
                'verbose_name_plural': 'Alertas tempranas',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
