# Generated by Django 4.2.29 on 2026-03-24 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de alerta',
                'verbose_name_plural': 'Tipos de alerta',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='alertatemprana',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='alertatemprana',
            name='nivel',
            field=models.CharField(choices=[('ATENCION', 'Atención'), ('RIESGO', 'Riesgo'), ('CRITICO', 'Crítico')], max_length=20),
        ),
        migrations.CreateModel(
            name='ConfiguracionAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('operador', models.CharField(choices=[('>=', 'Mayor o igual que'), ('>', 'Mayor que'), ('<=', 'Menor o igual que'), ('<', 'Menor que'), ('==', 'Igual a')], default='>=', max_length=2)),
                ('umbral', models.DecimalField(decimal_places=2, max_digits=8)),
                ('nivel', models.CharField(choices=[('ATENCION', 'Atención'), ('RIESGO', 'Riesgo'), ('CRITICO', 'Crítico')], max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='alertas.tipoalerta')),
            ],
            options={
                'verbose_name': 'Configuración de alerta',
                'verbose_name_plural': 'Configuraciones de alerta',
                'ordering': ['tipo_alerta', 'umbral'],
            },
        ),
        migrations.AddField(
            model_name='alertatemprana',
            name='configuracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_generadas', to='alertas.configuracionalerta'),
        ),
        migrations.AddField(
            model_name='alertatemprana',
            name='tipo_alerta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_generadas', to='alertas.tipoalerta'),
        ),
    ]
