# Generated by Django 4.2.29 on 2026-04-10 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alertas', '0002_tipoalerta_remove_alertatemprana_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CONTACTO_ACUDIENTE', 'Contacto con acudiente'), ('APOYO_PEDAGOGICO', 'Apoyo pedagogico'), ('REMISION_ORIENTACION', 'Remision a orientacion'), ('COMPROMISO_ACADEMICO', 'Compromiso academico'), ('OBSERVACION', 'Observacion')], max_length=30)),
                ('descripcion', models.TextField()),
                ('resultado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('MEJORA', 'Presenta mejora'), ('SIN_MEJORA', 'Sin mejora'), ('CERRADO', 'Caso cerrado')], default='PENDIENTE', max_length=20)),
                ('proxima_revision', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='alertas.alertatemprana')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_alertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento de alerta',
                'verbose_name_plural': 'Seguimientos de alertas',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
