# Generated by Django 4.2.29 on 2026-04-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auditoriacambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COORD', 'Coordinador'), ('DOC', 'Docente'), ('EST', 'Estudiante')], default='DOC', max_length=10),
        ),
        migrations.AddIndex(
            model_name='auditoriacambio',
            index=models.Index(fields=['tipo', '-fecha_creacion'], name='audit_tipo_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriacambio',
            index=models.Index(fields=['modulo', '-fecha_creacion'], name='audit_modulo_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriacambio',
            index=models.Index(fields=['estudiante_codigo', '-fecha_creacion'], name='audit_estudiante_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacionusuario',
            index=models.Index(fields=['usuario', 'leida', '-fecha_creacion'], name='notif_usuario_leida_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacionusuario',
            index=models.Index(fields=['tipo', '-fecha_creacion'], name='notif_tipo_fecha_idx'),
        ),
    ]
